### ISSUE TITLE
[BUG] Car being reset to sport engine and stock brakes 

### ISSUE THREAD

**Issue by SterlingMoss** [ParadoxGamingRP/paradox-bugs#323]
SterlingMoss#1596

This is happened to me three times, and I'm not sure if this is car specific but at this point I believe this is worthy of a bug report. My Banshee keeps getting the engine reset to sport engine and stock brakes, and for whatever the reason the horn is being reset as well. It does not need to be parked in a garage for this to happen, I reapplied my engine upgrade then parked my car at the VU for work and when I got back in my car it was at sport engine and stock brakes. Unsure how to reproduce the bug without having a fully upgraded Banshee.

**To Reproduce**

1. fully upgrade banshee
2. leave it somewhere for a bit
3. drive again and go check bennys to see if upgrades stayed 

**Expected behavior**
expect my upgrades to stay

**Screenshots**
![2022-03-21 (8)](https://user-images.githubusercontent.com/97280265/159596303-010a8290-c940-42e7-8763-ed270b4966d1.png)
![2022-03-21 (12)](https://user-images.githubusercontent.com/97280265/159596316-7f329863-07cd-4c6d-a319-0465df87d873.png)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
@SterlingMoss is this still happening?

**Comment by JnKTechstuff** [comment]
Sufficient time has passed
