### ISSUE TITLE
[BUG] Body armor

### ISSUE THREAD

**Issue by HoneySharks** [ParadoxGamingRP/paradox-bugs#383]
**Your Discord Name**
HoneySharks#2021
**Describe the bug**
So yesterday I was in a shootout my armor in my stream was at like 25%, Flew in today and now it is at half. I might have changed my clothes with the body armor on so i am not sure if that would be the problem
**To Reproduce**
[Steps to reproduce the bug]
1. Allow body armor to be removed
2. Make body armor less durable 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
I would expect it to either break/be able to be removed

**Screenshots**
[If applicable, add screenshots to help explain your problem]
https://gyazo.com/5db99d7978f2ec97a0a5490e86770958
https://gyazo.com/04667ad5f5c37461d0ad4dd0c3658c12 From stream.
https://gyazo.com/854b4e5a5f2abc89f441e6ec319609fa also from the stream of it going down
https://clips.twitch.tv/ArtisticBlatantMouseNotATK-ZBTvh_vpryppJWip also a clip to show it goes away
**Logs**
[Add your FiveM logs]
[https://gyazo.com/35f294424024814affbeef3a351dcff6](https://gyazo.com/35f294424024814affbeef3a351dcff6)

**Comment by xXJamieXx** [comment]
I'm confused about what the bug this report is trying to explain is... Those aren't reproduction steps so its hard to understand what the issue here is.

**Comment by JnKTechstuff** [comment]
Unable to figure out
