### ISSUE TITLE
[BUG] Texts and recent calls don't show up

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/paradox-bugs#429]
**Your Discord Name**
Weeb#5266

**Describe the bug**
Recent texts don't open until I send someone a message and if I receive a message from someone it doesn't open the conversation which makes texting back unknown numbers impossible, also recent calls don't work either so if I am unsure who has called me I can't call them back. Also as of 2 days ago some of the contacts that I already have do not show up as contacts when they call me but as their numbers.

**To Reproduce**
[Steps to reproduce the bug]
1. receive a text/call
2. check in app
3. don't see it

**Expected behavior**
When I receive a text or a call for me to be able to see it in the app with the message without having to text back

**Comment by JnKTechstuff** [comment]
This is long-term waiting on the new phone and we will be closing the issue rather than leave it open!
