### ISSUE TITLE
[BUG] Suspension upgrade wont stay on my ardent. 

### ISSUE THREAD

**Issue by Iwear0000FF** [ParadoxGamingRP/paradox-bugs#459]
### Your Discord Name

Play3r0000FF#9352

### A clear and concise description of what the bug is

I bought The suspension and Transmission upgrades for the ardent and they dissapeared. I then got given a refund and re applied them. On my way to the apartments to park i crashed into a local and went to repair it so i didnt park it broken and the suspension was gone again. I then went and parked it and made another report where i was told to come here. I did also try to reapply it after it had been parked out of my own pocket and then parked it and checked again and it was gone. 

### Steps to Reproduce the Bug

upgrade the ardent. 
Repair it.
Upgrades are back to stock.

### Expected Behavior

I didnt think i would lose them. I thought if i parked it the upgrades would stay this time.

### Screenshots/Videos

![FiveM_b2545_GTAProcess_j6c4hHfOq0](https://user-images.githubusercontent.com/100473322/168083985-a99874bc-b9b4-41c5-a2c7-21b50be1320a.jpg)
![FiveM_b2545_GTAProcess_dAM4jELP4X](https://user-images.githubusercontent.com/100473322/168084077-ad352abb-311b-483f-83ef-97f8fec3e63f.jpg)

### Extra Notes (Optional)

also you can see it says my car has no clutch installed at all.

**Comment by Sly-Panda** [comment]
Got logs?

**Comment by Iwear0000FF** [comment]
Hey sly  I sure do. I also have another from after i made the report if needed.
[CitizenFX_log_2022-05-12T051923.log](https://github.com/xXJamieXx/paradox-bugs/files/8683099/CitizenFX_log_2022-05-12T051923.log)

**Comment by Sly-Panda** [comment]
This should have been fixed with an earlier update to save mods when they are purchased, is this still happening?

**Comment by JnKTechstuff** [comment]
Sufficient time has passed
