### ISSUE TITLE
[BUG] Faggio Sport Wheel Options

### ISSUE THREAD

**Issue by MCSplashdown** [ParadoxGamingRP/paradox-bugs#477]
**Your Discord Name**
M.C. Splashdown#5165

**Describe the annoyance**
[When attempting to change the tires on the faggio sport, it allows me to change the front tire without any issues, but when I try to replace the back tire it won't let me and there isn't any options that allow me to change this back tire either so it remains as stock no matter what I try.]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go to a mechanic shop with a faggio sport.
2. Go through the customization options and go to the wheel options.
3. Try and change the tires but it only lets you change the front tire and not the back one

**Requested behavior**
[There should be a way to change the back tire on the faggio sport as well, from what I heard this seems to be an issue with more bikes other than just the faggio sport.]

**Screenshots**
https://cdn.discordapp.com/attachments/978820336076337183/978867474407772201/unknown.png
https://cdn.discordapp.com/attachments/978820336076337183/979135881468325988/unknown.png

**Additional context**
[Maybe a separate option for the back wheels might help for bikes like the faggio sport, cause I think it works for the faggio mod.]

**Comment by Sly-Panda** [comment]
Do you mean the tyres or the wheels?  Have tested with it and the wheels both front and back can be customized.  Make sure you have stored the bike after buying it and then check to see if it works.

![image](https://user-images.githubusercontent.com/43046128/170845455-d1cc75d3-98a3-48f8-953a-56dfde2b391a.png)

If it continues to happen if you could hit F8 > Open Log > File > Save As and drop that log in here we can look into it a bit more.

**Comment by MCSplashdown** [comment]
Thank you for taking the time to address this issue, unfortunately after
attempting it several times, and going through almost all the settings, it
still won't let me customize the back tire, both for the back tire itself
and the rims of the tire as well.I have stored it, taken it to the LS
Customs and still end up with a similar result. Maybe you'll have better
luck figuring out the issue in the citizen log, but for now I can't figure
out how to resolve this issue. Once again thank you and I'm glad I chose
this server to RP in.

**Comment by Sly-Panda** [comment]
If you can drop your logs in here after you take the bike into a customs and try change the wheels/not get the options popping up we can go through them and see if there's a reason it's not showing you the options.

I haven't been able to reproduce it so need to have a look through your logs to see if I can work out the cause.

**Comment by xXJamieXx** [comment]
Your logs are not coming through. You probably need to reply via the website instead.

**Comment by MCSplashdown** [comment]
[CitizenFX_log_2022-06-03T221036.log](https://github.com/xXJamieXx/paradox-bugs/files/8836140/CitizenFX_log_2022-06-03T221036.log)

**Comment by MCSplashdown** [comment]
[CitizenFX_log_2022-06-01T071747.log](https://github.com/xXJamieXx/paradox-bugs/files/8836143/CitizenFX_log_2022-06-01T071747.log)

**Comment by MCSplashdown** [comment]
I hope these 2 logs will help you.
