### ISSUE TITLE
[BUG] Spooky Bins at Munja Munja Cause Invisibility

### ISSUE THREAD

**Issue by CorFinn** [ParadoxGamingRP/paradox-bugs#502]
### Your Discord Name

GrandNagus#9705

### A clear and concise description of what the bug is

Climbing on the bins outside Munja Munja's (looking at the building from the front, (they are on the front right side) will cause you to gain invisibility.

### Steps to Reproduce the Bug

1. Visit MunjaMunja
2. Attempt to climb on top of a bin.
3. Win your chance at invisibility! (works about 50% of the time)

A soft relog fixes it, but I should probably move/remove those bins.

### Expected Behavior

I didn't expect invisibility, but I wasn't mad about it either. When I climb atop a garbage bin, I expect high ground advantage.

### Screenshots/Videos

https://i.imgur.com/PFSydBE.gif

**Comment by CorFinn** [comment]
[CitizenFX_log_2022-06-15T225956.log](https://github.com/xXJamieXx/paradox-bugs/files/8914306/CitizenFX_log_2022-06-15T225956.log)

**Comment by madsskyy** [comment]
should be fixed next restart
