### ISSUE TITLE
[BUG] duplicate cars?

### ISSUE THREAD

**Issue by madsskyy** [ParadoxGamingRP/paradox-bugs#539]
### Your Discord Name

madsskyy #2165

### A clear and concise description of what the bug is

not sure how this happened but we had duplicate cars, the keys given to one transferred to the other, same damage, same plate, etc.

### Steps to Reproduce the Bug

i have no idea. maybe just have the car exist?

### Expected Behavior

there wouldn't be 2 cars

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/103598492/176983945-2285b9e9-2caa-4c98-9fd7-f87babd38a4d.png)
![image](https://user-images.githubusercontent.com/103598492/176983962-4ce0a25a-07ec-40b4-a5c4-ecd3b3dc74a9.png)

**Comment by Lucius243** [comment]
My logs durring the issue
[CitizenFX_log_2022-07-02T023804.log](https://github.com/xXJamieXx/paradox-bugs/files/9032287/CitizenFX_log_2022-07-02T023804.log)

**Comment by xXJamieXx** [comment]
Need more substantial information this. I literally have nothing to go on. The log provided is also from a completely separate instance of FiveM when it has barely launched the game let alone connected to the server. Overall I don't have anything to go on with this so need more information...

**Comment by madsskyy** [comment]
i honestly have no idea how it happened, but it did. thats literally all i can say man.

**Comment by Lucius243** [comment]
oh shit must have been the wrong log sorry guys

**Comment by xXJamieXx** [comment]
Not enough info to proceed with this.
