### ISSUE TITLE
[BUG]  City Hall Parking Not working

### ISSUE THREAD

**Issue by stbadreturns** [ParadoxGamingRP/paradox-bugs#561]
### Your Discord Name

Stbadreturns#9043

### A clear and concise description of what the bug is

I cant park my car in at city hall

### Steps to Reproduce the Bug

drive up doesn't let me park
get out says it an available parking area
get back in car and its gone

### Expected Behavior

park my car like other car parks

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/47409242/179096225-c73a1c40-881f-4dde-b7d5-9f764aa568ac.png)
![image](https://user-images.githubusercontent.com/47409242/179096265-2580dc21-eb34-4444-ab02-29e3e3cea4ed.png)

### Extra Notes (Optional)

don't know if it because of a particular vehicle its a tailgater S

**Comment by JnKTechstuff** [comment]
Tested; works for me the area is only in the corner of city hall to prevent people from blocking it
