### ISSUE TITLE
Car License Plate Text Change Makes Character Lose Car Keys

### ISSUE THREAD

**Issue by jaredvalencia** [ParadoxGamingRP/paradox-bugs#564]
### Your Discord Name

AK47#0001

### A clear and concise description of what the bug is

The bug is when you change the license plate text on your car through Los Santos Customs, and what happens is after you change the text the car just stops working, and you can't change the engine on and off for it to work. What solved the issue was hotwiring the vehicle and then it started to function normally again after the purchase. 

### Steps to Reproduce the Bug

1. Go to Los Santos Customs
2. Purchase a license plate text change
3. Change the text 
4. Now the car should be non-working until you hotwire it

### Expected Behavior

I expected the car to function normally after any typical purchase or extras for your vehicle at Los Santos customs. 

### Screenshots/Videos

I don't have any screenshots, because the issue was solved, but the car acts as if you stole a local's car until you hotwire your vehicle again. 

### Log File

[CitizenFX_log_2022-07-15T063818.log](https://github.com/xXJamieXx/paradox-bugs/files/9123189/CitizenFX_log_2022-07-15T063818.log)

**Comment by SpiceF0x** [comment]
Here's me getting my car out Jamie where I lose my keys, too:
![20220715224341_1](https://user-images.githubusercontent.com/96963965/179315079-1e72a0cd-3499-4ede-9624-54a387941332.jpg)

**Comment by JnKTechstuff** [comment]
Possible fix pushed in summer update
