### ISSUE TITLE
[BUG] <Car sells for $0>

### ISSUE THREAD

**Issue by TweakinT** [ParadoxGamingRP/paradox-bugs#569]
### Your Discord Name

TweakinT#6020

### A clear and concise description of what the bug is

Went to sell my car and it shows it sells for $0, elegy RH8, same thing happened to my buddy in his sentinel classic. was told to put a bug report in for it.
![unknown](https://user-images.githubusercontent.com/101960870/179384159-39447a0c-bf1f-4ca7-aeb5-5899356f1465.png)
 

### Steps to Reproduce the Bug

try to sell my car.

### Expected Behavior

Sell for a certain % of purchase price like usual.

### Screenshots/Videos

![unknown](https://user-images.githubusercontent.com/101960870/179384193-2f599798-6f60-466e-b585-ec7e16941e4b.png)

### Log File

[CitizenFX_log_2022-07-17T022033.log](https://github.com/ParadoxGamingRP/paradox-bugs/files/9127045/CitizenFX_log_2022-07-17T022033.log)

**Comment by madsskyy** [comment]
also having this issue with my elegy retro custom

**Comment by xXJamieXx** [comment]
Was missing a 0 in my math calculation so it was decreasing the value by too much. Should be fixed after restart.
