### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WraithKildare** [ParadoxGamingRP/paradox-bugs#571]
### Your Discord Name

Wraith

### A clear and concise description of what the bug is

I can not store the Mule at our gang garage or any other public garage. When I scuff impound it, it works fine. Thanks!

### Steps to Reproduce the Bug

Tried to store the Mule at multiple garages throughout the city. 

### Expected Behavior

mule goes into the garage

### Screenshots/Videos

https://imgur.com/a/ktDBisz

### Extra Notes (Optional)

Help!

**Comment by Sly-Panda** [comment]
Fixed next update
