### ISSUE TITLE
[BUG] Flare gun no ammo

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/paradox-bugs#572]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

When buying a flare gun and trying to use it, there isn't any ammo sold at the gun store to load it with, and pistol ammo doesn't work. I remember in the town hall Jake said it was going to use pistol ammo so not sure if that's intended or not.

### Steps to Reproduce the Bug

 1. Buy flare gun
 2. try to load gun/buy flare ammo
 3. nothing

### Expected Behavior

I expect the flare gun to use pistol ammo or for the gun store to sell ammo for it.

### Screenshots/Videos

https://streamable.com/5rcs8x

### Log File

[CitizenFX_log_2022-07-17T172648.log](https://github.com/ParadoxGamingRP/paradox-bugs/files/9128340/CitizenFX_log_2022-07-17T172648.log)

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
