### ISSUE TITLE
[ENHANCEMENT] CID Taurus for Motor Pool

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/paradox-bugs#574]
**Your Discord Name**
OwlCherry#6969

**Describe the annoyance**
Can we have the CID motor pool taurus set with livery#6 (no livery) and extras 2,3 and 9. currently it pulls out as LSPD.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Sly-Panda** [comment]
To my knowledge none of the departments were given any Taurus and had to purchase them themselves.  I may be corrected on this but if not you will just need to take the one someone purchased there to bennies and customize it to your liking and re-store it back in your motorpool.

**Comment by Sly-Panda** [comment]
Looks like motorpool won't actually save the extras/livery so we'll get that sorted for ya.

**Comment by xXJamieXx** [comment]
Fixed next restart.

**Comment by OwlCherry** [comment]
thanks guys
